Name: autoMail-api
Host: 0.0.0.0
Port: 8081
Mode: dev
DataSource:
  DataSourceName: "xxx:xxx@tcp(xxx:3306)/trade?charset=utf8mb4&parseTime=True&loc=Local"

Log:
  ServiceName: automail
  Level: info
  Mode: file
  MaxSize: 5
  KeepDays: 60

SmtpSource:
  Server: smtp.163.com
  Port: 465
  Username:
  Password:

PopSource:
  Server: pop.qq.com
  Port: 995
  Username:
  Password: