Name: autoMail-api
Host: 0.0.0.0
Port: 8081
Mode: dev
DataSource:
  DataSourceName: "root:1234abcd@tcp(38.89.73.173:3306)/trade?charset=utf8mb4&parseTime=True&loc=Local"

Log:
  ServiceName: automail
  level: info
  Mode: file
  MaxSize: 500
  KeepDays: 60

