// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Email string `form:"email"`
	Token string `form:"token"`
}

type Response struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}
