// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"automail/autoMail/internal/svc"
	"fmt"
	"github.com/zeromicro/go-zero/rest"
	"net/http"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	fmt.Println(server)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/unsubscribe/:email/:token",
				Handler: UnsubscribeHandler(serverCtx),
			},
		},
	)
}
